# Generated by Django 3.0.6 on 2020-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.CharField(max_length=100, unique=True)),
                ('mutual_funds_name', models.CharField(default=None, max_length=100)),
                ('date', models.CharField(default=None, max_length=100)),
                ('price', models.FloatField(default=None, max_length=100)),
                ('status', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'MutualFunds',
            },
        ),
    ]
