# Generated by Django 3.0.6 on 2020-05-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISINapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunds',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
