# Generated by Django 3.0.6 on 2020-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISINapp', '0002_auto_20200525_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunds',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
