# Generated by Django 3.0.6 on 2020-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISINapp', '0003_auto_20200525_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunds',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
